In [1]:
import numpy as np

arrange function
1. arange(end) : starting from 0 to end-1
2. arange(start, end) : starting from start to end-1
3. arange(start, end, step) : starting from start to end-1 with stepsize

In [11]:
arrayA = np.arange(0,5,0.5)
arrayA

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [21]:
lst = [[1, 2, 3], 
       [4, 5, 6]]
lst

[[1, 2, 3], [4, 5, 6]]

In [27]:
arrayB = np.array(lst)
print(arrayB)
print(arrayB.dtype)

[[1 2 3]
 [4 5 6]]
int32


In [30]:
int32 = arrayB.astype(np.int64)
int32

array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

In [32]:
int32.size

6

In [33]:
int32.ndim

2

In [35]:
len(int32.shape)

2

In [36]:
int32.shape

(2, 3)

Array constructions

In [40]:
np.ones((2,3), dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1]])

In [41]:
np.zeros((2,3), dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0]])

In [42]:
np.ones((2,3), dtype=np.int32) + 4

array([[5, 5, 5],
       [5, 5, 5]])

In [48]:
np.empty((2,3), dtype=np.int32)

array([[  849641120,         713,           0],
       [          0,      131074, -2147483648]])

In [53]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
np.diag((1,2,3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [56]:
np.linspace(6, 10, num=10)

array([ 6.        ,  6.44444444,  6.88888889,  7.33333333,  7.77777778,
        8.22222222,  8.66666667,  9.11111111,  9.55555556, 10.        ])